### ISSUE TITLE
Bower icons are lost

### ISSUE THREAD

**Issue by vrubezhny** [sbegaudeau/webtools.jsdt#1]
Bower UI icons are lost:

!ENTRY org.eclipse.jface 4 0 2014-12-17 21:02:08.337
!MESSAGE /icons/bower-logo_16x16.png
!STACK 0
java.io.FileNotFoundException: /icons/bower-logo_16x16.png
    at org.eclipse.osgi.storage.url.bundleentry.Handler.findBundleEntry(Handler.java:37)
    at org.eclipse.osgi.storage.url.BundleResourceHandler.openConnection(BundleResourceHandler.java:169)
    at java.net.URL.openConnection(URL.java:972)
    at org.eclipse.core.internal.boot.PlatformURLConnection.connect(PlatformURLConnection.java:110)
    at org.eclipse.core.internal.boot.PlatformURLConnection.getURLAsLocal(PlatformURLConnection.java:241)
    at org.eclipse.core.internal.runtime.PlatformURLConverter.toFileURL(PlatformURLConverter.java:36)
    at org.eclipse.core.runtime.FileLocator.toFileURL(FileLocator.java:206)
    at org.eclipse.jface.resource.URLImageDescriptor.getFilePath(URLImageDescriptor.java:128)
    at org.eclipse.jface.resource.URLImageDescriptor.createImage(URLImageDescriptor.java:143)
    at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:224)
    at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:202)
    at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.getImageFromURI(SWTPartRenderer.java:225)

**Comment by sbegaudeau** [comment]
This issue has been fixed: https://github.com/sbegaudeau/webtools.jsdt/commit/85d95145792b6cb993dd7c928ce86eea66e5c752
